[2020-06-27 01:08:09] [[31merror[39m] MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb mongodb:27017
    at NativeConnection.Connection.openUri (/home/tinh/Documents/NodeJS/VDsocial/server/node_modules/mongoose/lib/connection.js:830:32)
    at Mongoose.connect (/home/tinh/Documents/NodeJS/VDsocial/server/node_modules/mongoose/lib/index.js:335:15)
    at Object.<anonymous> (/home/tinh/Documents/NodeJS/VDsocial/server/app.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[2020-06-27 01:09:33] [[31merror[39m] MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb mongodb:27017
    at NativeConnection.Connection.openUri (/home/tinh/Documents/NodeJS/VDsocial/server/node_modules/mongoose/lib/connection.js:830:32)
    at Mongoose.connect (/home/tinh/Documents/NodeJS/VDsocial/server/node_modules/mongoose/lib/index.js:335:15)
    at Object.<anonymous> (/home/tinh/Documents/NodeJS/VDsocial/server/app.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
